#!/usr/bin/python3

import argparse
import time
from datetime import timedelta


def debug(msg):
    if args.verbose:
        print(f'\033[2m-V-\033[0m {msg}')

def wide_help_formatter(formatter, w=120, h=36):
    try:
        kwargs = {'width': w, 'max_help_position': h}
        formatter(None, **kwargs)
        return lambda prog: formatter(prog, **kwargs)
    except TypeError:
        return formatter

def getArgs():
    ap = argparse.ArgumentParser(
        add_help=False,
        formatter_class=wide_help_formatter(argparse.MetavarTypeHelpFormatter)
    )
    ap.description = f'\033[1m{page}\033[0m:\n{problem}'

    args = ap.add_argument_group('Arguments')
    args.add_argument('-t', '--target', default=4000000, type=int, help='Target value for fibonacci sequence to not exceed. Default=4000000')

    flgs = ap.add_argument_group('Flags')
    flgs.add_argument('-v', '--verbose', action='store_true', default=False, help='Verbose mode -> print debug messages')
    flgs.add_argument('-h', '--help', action='help', default=argparse.SUPPRESS, help='Show this help message and exit.')

    return ap.parse_args()


def solve(args):
    x,y,z = 0, 0, 1
    vals = []
    while z < args.target:
        debug(f'x: {x:5d} | y: {y:5d} | z: {z:5d}')
        if z%2 == 0:
            vals.append(z)
        x=y
        y=z
        z = x+y
    vals = list(set(vals))
    debug(f'evens: {vals}')
    return sum(list(set(vals)))

if __name__ == '__main__':
    page = 'https://projecteuler.net/problem=2}'
    problem = 'Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'
    args = getArgs()
    tic = time.time(); solution = solve(args); toc = time.time()
    print(f'\033[1mPrompt\033[0m: {problem}')
    print(f'[{timedelta(seconds=toc-tic)}] \033[1m\033[92manswer\033[0m: {solution}')
